blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/stefangrosse/thermal-brain/discussions
    about: Ask questions or start a discussion before opening an issue.
